run:
  - go run main.go
  - go test -v ./...
  - go vet ./...
  - go fmt ./...
  - go build
  - go install
  - go test -v ./...
  - go run main.go
   
  tests: true

test:
  script:
    - go test -v ./...  
    -coverprofile=coverage.txt  
    -covermode=atomic 
    -coverpkg=./... 
    -count=1  
    -race 
    -short  
    -tags=integration 
    -v
    

linters:
  disable-all: false
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    # - rowserrcheck -- disabled because of https://github.com/golangci/golangci-lint/issues/2649
    - staticcheck
    # - structcheck -- disabled because of https://github.com/golangci/golangci-lint/issues/2649
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - yacccheck
    - yamllint
    - yamlfix
    - yamltags
    - yamlindent
    - yamllint
    - yamltags
    - yamlfix

linters-settings:
  gocyclo: true
  gofmt: true
  goprintffuncname: true
  gosimple: true
  govet: true
  goprintffuncname: true
  gocritic: true
  deadcode: true
  nakedret: true
  revive: true
  staticcheck: true
  typecheck: true
  unconvert: true
  varcheck: true

  goimports:
    local-prefixes: github.com/stripe/stripe-cli
  misspell:
    locale: US
  yamlfix: 
    local-prefixes: github.com/stripe/stripe-cli
  yamltags:
    local-prefixes: github.com/stripe/stripe-cli
  yamlfix:
    local-prefixes: github.com/stripe/stripe-cli  

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

